import{a as y}from"./assets/vendor-Cn2Vr82J.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const h="46071248-68730f1ac11d3747a84542f11",g="https://pixabay.com/api/";async function d(t,o=1){try{return(await y.get(`${g}`,{params:{key:h,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(n){throw console.error("Error fetching images:",n),n}}function u(t){const o=document.getElementById("gallery"),n=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:f,comments:m,downloads:p})=>`<a href="${e}" class="gallery-item">
                <img src="${i}" alt="${r}" loading="lazy" />
                <div class="info">
                    <p>Likes ${s}</p>
                    <p>Views ${f}</p>
                    <p>Comments ${m}</p>
                    <p>Downloads ${p}</p>
                </div>
            </a>`).join("");o.insertAdjacentHTML("beforeend",n)}function L(){const t=document.getElementById("gallery");t.innerHTML=""}let a=1,l="";const E=document.getElementById("search-form"),c=document.getElementById("load-more");E.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.query.value.trim(),!!l){a=1,L(),c.hidden=!0;try{const o=await d(l,a);u(o.hits),o.totalHits>15&&(c.hidden=!1)}catch(o){console.error(o)}}});c.addEventListener("click",async()=>{a+=1;try{const t=await d(l,a);u(t.hits),a*15>=t.totalHits&&(c.hidden=!0,alert("We're sorry, but you've reached the end of search results."))}catch(t){console.error(t)}});function v(){const{height:t}=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}c.addEventListener("click",async()=>{v()});
//# sourceMappingURL=index.js.map
