import{a as b,S as w,i as l}from"./assets/vendor-mdVVRe9K.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const S="46071248-68730f1ac11d3747a84542f11",v="https://pixabay.com/api/";async function E(e,o=1,i=15){try{return(await b.get(v,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:i}})).data}catch(s){throw console.error("Error fetching images:",s),s}}function P(e,o){const i=e.map(({webformatURL:s,largeImageURL:t,tags:r,likes:c,views:g,comments:p,downloads:L})=>`
            <a href="${t}" class="gallery-item">
                <img src="${s}" alt="${r}" loading="lazy" />
                <div class="info">
                    <p><b>Likes</b> ${c}</p>
                    <p><b>Views</b> ${g}</p>
                    <p><b>Comments</b> ${p}</p>
                    <p><b>Downloads</b> ${L}</p>
                </div>
            </a>
        `).join("");o.insertAdjacentHTML("beforeend",i)}function q(e){e.innerHTML=""}const $=document.querySelector("#search-form"),h=document.querySelector(".gallery"),n=document.querySelector("#load-more"),d=document.querySelector(".loader");let O=new w(".gallery a"),a=1,u="",f=0;n.classList.add("hidden");d.classList.add("hidden");$.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.currentTarget.elements.searchQuery.value.trim(),!u){l.error({title:"Error",message:"Search query cannot be empty!"});return}a=1,f=0,q(h),n.classList.add("hidden"),await y()});n.addEventListener("click",async()=>{a+=1,await y()});async function y(){m(!0),n.classList.add("hidden");try{const e=await E(u,a);if(f=e.totalHits,e.hits.length===0&&a===1){l.info({title:"Sorry",message:"No images found. Please try again!"});return}P(e.hits,h),O.refresh(),a>1&&H();const o=Math.ceil(f/15);a>=o?(l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("hidden")):n.classList.remove("hidden")}catch{l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{m(!1)}}function H(){const{height:e}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function m(e){e?d.classList.remove("hidden"):d.classList.add("hidden")}
//# sourceMappingURL=index.js.map
